In [11]:
import torch 
import numpy as np

In [9]:
tensor = torch.ones(2,3,4) 
tensor.sum(1) 



tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [13]:
tensor = torch.from_numpy(np.arange(18).reshape(6,3)) 


In [15]:
tensor[:2,:]

tensor([[0, 1, 2],
        [3, 4, 5]], dtype=torch.int32)

In [16]:
tensor[2:,:]

tensor([[ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]], dtype=torch.int32)

In [22]:
cc = tensor[1,:]-tensor[2,:]

In [23]:
cb = torch.cat((tensor[1,:],tensor[2,:]),0)

In [27]:
ca = torch.dot(tensor[1,:],tensor[2,:]) 
cf = torch.from_numpy(np.array([ca]))

In [28]:
torch.cat((cf,cb,cc) , 0)

tensor([86,  3,  4,  5,  6,  7,  8, -3, -3, -3], dtype=torch.int32)

In [31]:
tensor.sum(0)

tensor([45, 51, 57])

In [40]:
tenstest = torch.ones(2,3,4) 
ca= tenstest.sum(1)
tentest2 = torch.ones(2,3,4) 
tentest2 = tentest2 + 1
cb = tentest2.sum(1) 
print(ca) 
print(cb)
da = ca-cb 
concab = torch.cat((ca,cb),1) 
print(da) 
print(concab) 
finab = torch.cat((da,concab) , 1) 
print(finab)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.]])
tensor([[-3., -3., -3., -3.],
        [-3., -3., -3., -3.]])
tensor([[3., 3., 3., 3., 6., 6., 6., 6.],
        [3., 3., 3., 3., 6., 6., 6., 6.]])
tensor([[-3., -3., -3., -3.,  3.,  3.,  3.,  3.,  6.,  6.,  6.,  6.],
        [-3., -3., -3., -3.,  3.,  3.,  3.,  3.,  6.,  6.,  6.,  6.]])


In [47]:
torch.dot(ca[0,:],cb[0,:],out = torch.tensor([1.0]))

C:\Users\msgto\AppData\Local\Temp\ipykernel_24504\2918899180.py:1: UserWarning: An output with one or more elements was resized since it had shape [1], which does not match the required output shape [].This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at  C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\Resize.cpp:24.)
  torch.dot(ca[0,:],cb[0,:],out = torch.tensor([1.0]))


tensor(72.)

In [53]:
c = torch.tensor([[]]) 
for i in range(2): 
    c = torch.cat((c,torch.tensor([[torch.dot(ca[i,:],cb[i,:])]])),0) 
print(c)

RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 0 but got size 1 for tensor number 1 in the list.